/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './features/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        surface: '#0e0e0e',
        'surface-dim': '#0e0e0e',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#131313',
        'surface-container': '#191a1a',
        'surface-container-high': '#1f2020',
        'surface-container-highest': '#252626',
        'surface-bright': '#2b2c2c',
        'surface-variant': '#252626',
        primary: '#d4bee4',
        'primary-dim': '#c6b1d6',
        'primary-fixed': '#f0dbff',
        'primary-fixed-dim': '#e3ccf3',
        'primary-container': '#51405f',
        'on-primary': '#4a3a58',
        'on-primary-fixed': '#493957',
        secondary: '#b8987a',
        'secondary-dim': '#b8987a',
        'secondary-fixed': '#ffdcbe',
        'secondary-fixed-dim': '#f2cead',
        'secondary-container': '#4e371f',
        'on-secondary': '#2f1c07',
        'on-secondary-container': '#dcb99a',
        'on-surface': '#e7e5e5',
        'on-surface-variant': '#acabaa',
        'on-background': '#e7e5e5',
        background: '#0e0e0e',
        outline: '#767575',
        'outline-variant': '#484848',
        error: '#ee7d77',
        'error-container': '#7f2927',
      },
      fontFamily: {
        headline: ['Lexend_700Bold'],
        'headline-extra': ['Lexend_800ExtraBold'],
        body: ['Lexend_400Regular'],
        'body-medium': ['Lexend_500Medium'],
        label: ['Lexend_600SemiBold'],
        'label-light': ['Lexend_300Light'],
      },
      borderRadius: {
        DEFAULT: '4px',
        lg: '8px',
        xl: '12px',
        '2xl': '16px',
        '3xl': '24px',
        '4xl': '32px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
