/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './features/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './lib/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        surface: '#0e0e0e',
        'surface-dim': '#0e0e0e',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#131313',
        'surface-container': '#191a1a',
        'surface-container-high': '#1f2020',
        'surface-container-highest': '#252626',
        'surface-bright': '#2b2c2c',
        'surface-variant': '#252626',
        primary: '#d4bee4',
        'primary-dim': '#c6b1d6',
        'primary-fixed': '#f0dbff',
        'primary-fixed-dim': '#e3ccf3',
        'primary-container': '#51405f',
        'on-primary': '#4a3a58',
        'on-primary-fixed': '#493957',
        secondary: '#b8987a',
        'secondary-dim': '#b8987a',
        'secondary-fixed': '#ffdcbe',
        'secondary-fixed-dim': '#f2cead',
        'secondary-container': '#4e371f',
        'on-secondary': '#2f1c07',
        'on-secondary-container': '#dcb99a',
        'on-surface': '#e7e5e5',
        'on-surface-variant': '#acabaa',
        'on-background': '#e7e5e5',
        background: '#0e0e0e',
        outline: '#767575',
        'outline-variant': '#484848',
        error: '#ee7d77',
        'error-container': '#7f2927',
        'surface-bright-glass': 'rgba(43,44,44,0.6)',
        'ob-bg': '#07090C',
        'ob-saffron': '#E07A5F',
        'ob-saffron-dim': 'rgba(224,122,95,0.15)',
        'ob-saffron-border': 'rgba(224,122,95,0.45)',
        'ob-gold': '#D9A06F',
        'ob-gold-dim': 'rgba(217,160,111,0.12)',
        'ob-gold-border': 'rgba(217,160,111,0.4)',
        'ob-text': '#F0EDE8',
        'ob-muted': '#8E8880',
        'ob-card': 'rgba(255,255,255,0.04)',
        'ob-card-border': 'rgba(255,255,255,0.09)',
        'ob-divider': 'rgba(255,255,255,0.07)',
      },
      fontFamily: {
        headline: ['GoogleSans_700Bold'],
        'headline-extra': ['GoogleSans_700Bold'],
        body: ['GoogleSans_400Regular'],
        'body-medium': ['GoogleSans_500Medium'],
        label: ['GoogleSans_600SemiBold'],
        'label-light': ['GoogleSans_400Regular'],
      },
      borderRadius: {
        DEFAULT: '4px',
        lg: '8px',
        xl: '12px',
        '2xl': '16px',
        '3xl': '24px',
        '4xl': '32px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
