/** @type {import('tailwindcss').Config} */
const themeColor = (name) => `rgb(var(--color-${name}) / <alpha-value>)`;

module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './features/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './lib/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        surface: themeColor('surface'),
        'surface-dim': themeColor('surface-dim'),
        'surface-container-lowest': themeColor('surface-container-lowest'),
        'surface-container-low': themeColor('surface-container-low'),
        'surface-container': themeColor('surface-container'),
        'surface-container-high': themeColor('surface-container-high'),
        'surface-container-highest': themeColor('surface-container-highest'),
        'surface-bright': themeColor('surface-bright'),
        'surface-variant': themeColor('surface-variant'),
        primary: themeColor('primary'),
        'primary-dim': themeColor('primary-dim'),
        'primary-fixed': themeColor('primary-fixed'),
        'primary-fixed-dim': themeColor('primary-fixed-dim'),
        'primary-container': themeColor('primary-container'),
        'on-primary': themeColor('on-primary'),
        'on-primary-fixed': themeColor('on-primary-fixed'),
        secondary: themeColor('secondary'),
        'secondary-dim': themeColor('secondary-dim'),
        'secondary-fixed': themeColor('secondary-fixed'),
        'secondary-fixed-dim': themeColor('secondary-fixed-dim'),
        'secondary-container': themeColor('secondary-container'),
        'on-secondary': themeColor('on-secondary'),
        'on-secondary-container': themeColor('on-secondary-container'),
        'on-surface': themeColor('on-surface'),
        'on-surface-variant': themeColor('on-surface-variant'),
        'on-background': themeColor('on-background'),
        background: themeColor('background'),
        outline: themeColor('outline'),
        'outline-variant': themeColor('outline-variant'),
        error: themeColor('error'),
        'error-container': themeColor('error-container'),
        'ob-bg': '#07090C',
        'ob-saffron': '#E07A5F',
        'ob-saffron-dim': 'rgba(224,122,95,0.15)',
        'ob-saffron-border': 'rgba(224,122,95,0.45)',
        'ob-gold': '#D9A06F',
        'ob-gold-dim': 'rgba(217,160,111,0.12)',
        'ob-gold-border': 'rgba(217,160,111,0.4)',
        'ob-text': '#F0EDE8',
        'ob-muted': '#8E8880',
        'ob-card': 'rgba(255,255,255,0.04)',
        'ob-card-border': 'rgba(255,255,255,0.09)',
        'ob-divider': 'rgba(255,255,255,0.07)',
      },
      fontFamily: {
        headline: ['CormorantGaramond_600SemiBold'],
        'headline-extra': ['CormorantGaramond_700Bold'],
        body: ['GoogleSans_400Regular'],
        'body-medium': ['GoogleSans_500Medium'],
        label: ['GoogleSans_600SemiBold'],
        'label-light': ['GoogleSans_400Regular'],
      },
      borderRadius: {
        DEFAULT: '4px',
        lg: '8px',
        xl: '12px',
        '2xl': '16px',
        '3xl': '24px',
        '4xl': '32px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
