/** @type {import('tailwindcss').Config} */
const themeColor = (name) => `rgb(var(--color-${name}) / <alpha-value>)`;

module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './features/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './lib/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        surface: themeColor('surface'),
        'surface-dim': themeColor('surface-dim'),
        'surface-container-lowest': themeColor('surface-container-lowest'),
        'surface-container-low': themeColor('surface-container-low'),
        'surface-container': themeColor('surface-container'),
        'surface-container-high': themeColor('surface-container-high'),
        'surface-container-highest': themeColor('surface-container-highest'),
        'surface-bright': themeColor('surface-bright'),
        'surface-variant': themeColor('surface-variant'),
        primary: themeColor('primary'),
        'primary-dim': themeColor('primary-dim'),
        'primary-fixed': themeColor('primary-fixed'),
        'primary-fixed-dim': themeColor('primary-fixed-dim'),
        'primary-container': themeColor('primary-container'),
        'on-primary': themeColor('on-primary'),
        'on-primary-fixed': themeColor('on-primary-fixed'),
        secondary: themeColor('secondary'),
        'secondary-dim': themeColor('secondary-dim'),
        'secondary-fixed': themeColor('secondary-fixed'),
        'secondary-fixed-dim': themeColor('secondary-fixed-dim'),
        'secondary-container': themeColor('secondary-container'),
        'on-secondary': themeColor('on-secondary'),
        'on-secondary-container': themeColor('on-secondary-container'),
        'on-surface': themeColor('on-surface'),
        'on-surface-variant': themeColor('on-surface-variant'),
        'on-background': themeColor('on-background'),
        background: themeColor('background'),
        outline: themeColor('outline'),
        'outline-variant': themeColor('outline-variant'),
        error: themeColor('error'),
        'error-container': themeColor('error-container'),
        'ob-bg': '#07090C',
        'ob-saffron': '#E07A5F',
        'ob-saffron-dim': 'rgba(224,122,95,0.15)',
        'ob-saffron-border': 'rgba(224,122,95,0.45)',
        'ob-gold': '#D9A06F',
        'ob-gold-dim': 'rgba(217,160,111,0.12)',
        'ob-gold-border': 'rgba(217,160,111,0.4)',
        'ob-text': '#F0EDE8',
        'ob-muted': '#8E8880',
        'ob-card': 'rgba(255,255,255,0.04)',
        'ob-card-border': 'rgba(255,255,255,0.09)',
        'ob-divider': 'rgba(255,255,255,0.07)',
        // ── Onboarding-new (hook-model redesign) palette — exact hex values from the HTML mock ──
        'obn-bg': '#0F0C08',
        'obn-bg2': '#0C0906',
        'obn-bg3': '#0B0906',
        'obn-gold': '#E8A33D',
        'obn-gold-bright': '#F0B454',
        'obn-gold-dim': 'rgba(232,163,61,0.14)',
        'obn-gold-border': 'rgba(232,163,61,0.35)',
        'obn-gold-border-soft': 'rgba(232,163,61,0.22)',
        'obn-text': '#F7F1E3',
        'obn-text-soft': '#F2EAD9',
        'obn-muted': 'rgba(242,234,217,0.6)',
        'obn-muted-dim': 'rgba(242,234,217,0.45)',
        'obn-card': 'rgba(242,234,217,0.04)',
        'obn-card-border': 'rgba(242,234,217,0.14)',
        'obn-ink': '#1A130A',
      },
      fontFamily: {
        headline: ['CormorantGaramond_600SemiBold'],
        'headline-extra': ['CormorantGaramond_700Bold'],
        body: ['GoogleSans_400Regular'],
        'body-medium': ['GoogleSans_500Medium'],
        label: ['GoogleSans_600SemiBold'],
        'label-light': ['GoogleSans_400Regular'],
        // ── Onboarding-new fonts — Cormorant Garamond (incl. italic) + Manrope, matching the HTML mock exactly ──
        'serif-regular': ['CormorantGaramond_400Regular'],
        'serif-medium': ['CormorantGaramond_500Medium'],
        'serif-semibold': ['CormorantGaramond_600SemiBold'],
        'serif-regular-italic': ['CormorantGaramond_400Regular_Italic'],
        'serif-medium-italic': ['CormorantGaramond_500Medium_Italic'],
        'serif-semibold-italic': ['CormorantGaramond_600SemiBold_Italic'],
        manrope: ['Manrope_400Regular'],
        'manrope-medium': ['Manrope_500Medium'],
        'manrope-semibold': ['Manrope_600SemiBold'],
        'manrope-bold': ['Manrope_700Bold'],
      },
      borderRadius: {
        DEFAULT: '4px',
        lg: '8px',
        xl: '12px',
        '2xl': '16px',
        '3xl': '24px',
        '4xl': '32px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
